# Generated by Django 5.0.5 on 2024-05-07 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adotar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoadocao',
            name='status',
            field=models.CharField(choices=[('AG', 'Aguardando Aprovação'), ('AP', 'Aprovado'), ('R', 'Recusado')], default='AG', max_length=2),
        ),
    ]
